language: node_js
node_js:
- 10.15.3
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.9.0
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
jobs:
  include:
  - stage: Unit tests
    script:
    - npm run test-unit
  - stage: Integration tests
    script:
    - sudo /etc/init.d/mysql stop
    - git clone https://github.com/streamr-dev/streamr-docker-dev.git
    - sudo ifconfig docker0 10.200.10.1/24
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start engine-and-editor"
    - sleep 3m
    - node node_modules/@streamr/streamr-p2p-network/bin/tracker.js &
    - npm run test-integration
  - stage: Deploy Staging
    script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - mkdir $TRAVIS_BUILD_DIR/upload
    - cp -r src  build
    - cp app.js build
    - cp package.json build
    - cp package-lock.json build
    - mv .codedeploy/appspec.yml build/appspec.yml
    - mv .codedeploy/ build/
    - cd build; tar -czvf $TRAVIS_BUILD_DIR/upload/broker-${TRAVIS_JOB_ID}.tar .; tar -czvf $TRAVIS_BUILD_DIR/upload/latest.tar .;
    - cd $TRAVIS_BUILD_DIR;
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: network-node/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: upload
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      key: network-node/releases/broker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-network-node-codedeploy
      deployment_group: eu-west-1-stg-network-node-deployment-group
      region: eu-west-1
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      key: network-node/releases/broker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-network-node-cassandra-codedeploy
      deployment_group: eu-west-1-stg-network-node-cassandra-deployment-group
      region: eu-west-1
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: d6p3qJF3YdCbs715yk1bRMzCjKfPtuidEHSAfkU54DzlVBG+SfugB01JeQ15KBmf9F1J5TJi3/OKibfv6jt7wJxAzhWy2AwJLIZWMEiQS6nVKaS3O2RbrEUTsWggySYrKjks3oy65AKaWyE2oGxi1+7jKxTafOIfKZ2djvFHICOOhbkswt6hFIBK++xj9NCal07UJ+2/89XChwnclH+XGh2nZ6Cdw1bOw63/Z1zgwwlrGpSpUYek2dkY2IrWcWlg7K/kIqAiiXuMglVGsPAceQYuKEXkK+Y6jVKcsJvNQoEcDUtDL1QLDEhqKGULzqza+uf636d+Uw0LNgrno6Yxa4H1TRN0yLMpSK5zLydDziIRaXGoQOfWN7hNXpXqMcxrpImgnw2tfDbVmvXiXVRA0SGEwxvjj3pb/dBPKgAH/IK7vR3EGRcv+94XcfN6+0YvEX/H/w6tbKHV/8Ud+3dBrtlP3TkrIHbT9Fncd/yHIlbOJ8/ZX845LTrhl2u9Qb4BMH1REIx9UFFrEPFmZ7k1mbeXgpl1x5X0b1LD/aVMQoFd2U419QmomTo523ggQ4+gu6+JgqhgEts9/6+AbcWbSwTDMlrj8Iy8XW05DbdGVFgTwfLodTXSg8OKL8ecSnsR4OyWspkpt0DCnZtD1W1bz/gnrTXNX+AMSp4du4fUsw0=
      bucket: eu-west-1-stg-streamr-vault
      key: network-node/releases/broker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-network-node-storage-codedeploy
      deployment_group: eu-west-1-stg-network-node-storage-deployment-group
      region: eu-west-1
  - stage: publish
    if: tag IS present
    script: npm publish
env:
  global:
    secure: YjBJm1GmSusUoHue15sAj04mZYhd6yC6v/V45hhyMhSfEawZn1H4nFzPiBqhNGZ2Lti2P+axJ5HXkFz/my/hWWL9+ENEKl0MczXcIWz5COZGZFJQORMCmL8u5yvFZvMqMGUwLuN6pkFnTHgYjRL7x7Ee+MEk+1qP0Tfy1qYaUhr192XzteRMI1zllxZSf3ElEY0BOjJ0N9PJs4O9X1T28w/lmW6c0ORiS9dCIG5afaMD50YRFrZCzc+l0e/kcSHo9lillCiD6755uTPBPYEmWYGmICRvG2qK+Hnv9B42sr3AOVKmkUyFHZgN1GOByHzcib8yrKdo2sgEr/oaFQvI2du915MDEAjMlQfeSbYjsPSouDMBD8CxhY6MVDwKZzMYF3KfSs7sttd411hx1vhog4aX+K6OFcVXyc/iSZAzSLSJQQvHrGffu5+lb/j7408vgJp69MAaK4ICfRhnGJbgcd/JxpGGeQiCELu1Zu7Sw8rXyq+W3ilvbOjfT0pXR9KzmZlFPpx083Ho51MxKoGEmxXL/RrW/LW5fx+EQXTuOQMnS+NUyJwPUUg16B0c+F2fNsov9KqXLiJBMXzo+fosjlWI+tm0pwNueFlGKJjs67Q/WwV5lKYyABQjTeBrT6AujGT7jeHHqp5ZrmKDLBHZK4isy63RqPeX+mwm/1fmHUU=
